export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_BLOGS_FAILED = 'GET_BLOGS_FAILED'
export const GET_BLOGS_LOADING = 'GET_BLOGS_LOADING'
export const GET_BLOGS = 'GET_BLOGS'

export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAILED = 'GET_REVIEWS_FAILED'
export const GET_REVIEWS_LOADING = 'GET_REVIEWS_LOADING'
export const GET_REVIEWS = 'GET_REVIEWS'

export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS'
export const GET_WORKS_FAILED = 'GET_WORKS_FAILED'
export const GET_WORKS_LOADING = 'GET_WORKS_LOADING'
export const GET_WORKS = 'GET_WORKS'

export const SET_LANGUAGE = 'SET_LANGUAGE'

export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'
export const POST_LOGIN_LOADING = 'POST_LOGIN_LOADING'
export const POST_LOGIN_DEFAULT = 'POST_LOGIN_DEFAULT'

export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const POST_MESSAGE_FAILED = 'POST_MESSAGE_FAILED'
export const POST_MESSAGE_LOADING = 'POST_MESSAGE_LOADING'
export const POST_MESSAGE_DEFAULT = 'POST_MESSAGE_DEFAULT'